foreground   #e6e6e7
cursor       #e6e6e7

color0       #0F0F0F
color8       #a1a1a1
color1       #807F7F
color9       #807F7F
color2       #8E8E8E
color10      #8E8E8E
color3       #A09FA1
color11      #A09FA1
color4       #AFAFAF
color12      #AFAFAF
color5       #C0BFC1
color13      #C0BFC1
color6       #D2D2D2
color14      #D2D2D2
color7       #e6e6e7
color15      #e6e6e7
